"""add_server_default_to_module_content_md

Revision ID: 4135dc685f0c
Revises: f2c4d44bae8c
Create Date: 2026-04-13 00:07:22.790446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4135dc685f0c'
down_revision: Union[str, Sequence[str], None] = 'f2c4d44bae8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_modules', 'content_md',
               existing_type=sa.TEXT(),
               server_default='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_modules', 'content_md',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
