"""tz_v3_org_topic_live_badge

Revision ID: 49c487a4e7d0
Revises: 45c8a7aaaece
Create Date: 2026-04-12 16:13:26.622928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c487a4e7d0'
down_revision: Union[str, Sequence[str], None] = '45c8a7aaaece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # UserRole enum ga yangi qiymatlar qo'shish (PostgreSQL ALTER TYPE)
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'org_admin'")
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'parent'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('school', 'learning_center', 'university', name='org_type'), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('stir', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free_trial', 'starter', 'growth', 'scale', name='org_plan'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'trial', name='org_status'), nullable=False),
    sa.Column('ai_token_limit', sa.Integer(), nullable=True),
    sa.Column('ai_tokens_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('organization_members',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_in_org', sa.Enum('org_admin', 'teacher', 'student', 'parent', name='org_member_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_org_id'), 'organization_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('organization_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='org_request_status'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_requests_id'), 'organization_requests', ['id'], unique=False)
    op.create_table('parent_students',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_students_id'), 'parent_students', ['id'], unique=False)
    op.create_index(op.f('ix_parent_students_parent_id'), 'parent_students', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_students_student_id'), 'parent_students', ['student_id'], unique=False)
    op.create_table('student_badges',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_badges_id'), 'student_badges', ['id'], unique=False)
    op.create_index(op.f('ix_student_badges_student_id'), 'student_badges', ['student_id'], unique=False)
    op.create_table('subjects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_org_id'), 'subjects', ['org_id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('game_type', sa.Enum('lucky_card', 'blitz', 'relay', 'question_duel', 'territory', 'pyramid', 'puzzle', name='game_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'finished', name='session_status'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_sessions_id'), 'live_sessions', ['id'], unique=False)
    op.create_table('live_session_teams',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_session_teams_id'), 'live_session_teams', ['id'], unique=False)
    op.create_index(op.f('ix_live_session_teams_session_id'), 'live_session_teams', ['session_id'], unique=False)
    op.create_table('topics',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content_latex', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['course_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_index(op.f('ix_topics_module_id'), 'topics', ['module_id'], unique=False)
    op.create_table('live_session_participants',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('personal_score', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('is_mvp', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['live_session_teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_session_participants_id'), 'live_session_participants', ['id'], unique=False)
    op.create_index(op.f('ix_live_session_participants_session_id'), 'live_session_participants', ['session_id'], unique=False)
    op.add_column('assignments', sa.Column('topic_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'assignments', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    op.add_column('classes', sa.Column('org_id', sa.UUID(), nullable=True))
    op.add_column('classes', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.add_column('classes', sa.Column('grade_level', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_classes_org_id'), 'classes', ['org_id'], unique=False)
    op.create_index(op.f('ix_classes_subject_id'), 'classes', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'classes', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'classes', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('courses', sa.Column('org_id', sa.UUID(), nullable=True))
    op.add_column('courses', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_courses_org_id'), 'courses', ['org_id'], unique=False)
    op.create_index(op.f('ix_courses_subject_id'), 'courses', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'courses', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'courses', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_column('users', 'org_id')
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_subject_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_org_id'), table_name='courses')
    op.drop_column('courses', 'subject_id')
    op.drop_column('courses', 'org_id')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_index(op.f('ix_classes_subject_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_org_id'), table_name='classes')
    op.drop_column('classes', 'grade_level')
    op.drop_column('classes', 'subject_id')
    op.drop_column('classes', 'org_id')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'topic_id')
    op.drop_index(op.f('ix_live_session_participants_session_id'), table_name='live_session_participants')
    op.drop_index(op.f('ix_live_session_participants_id'), table_name='live_session_participants')
    op.drop_table('live_session_participants')
    op.drop_index(op.f('ix_topics_module_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_live_session_teams_session_id'), table_name='live_session_teams')
    op.drop_index(op.f('ix_live_session_teams_id'), table_name='live_session_teams')
    op.drop_table('live_session_teams')
    op.drop_index(op.f('ix_live_sessions_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_subjects_org_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_student_badges_student_id'), table_name='student_badges')
    op.drop_index(op.f('ix_student_badges_id'), table_name='student_badges')
    op.drop_table('student_badges')
    op.drop_index(op.f('ix_parent_students_student_id'), table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_parent_id'), table_name='parent_students')
    op.drop_index(op.f('ix_parent_students_id'), table_name='parent_students')
    op.drop_table('parent_students')
    op.drop_index(op.f('ix_organization_requests_id'), table_name='organization_requests')
    op.drop_table('organization_requests')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_org_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
