"""add_class_code_expires_at

Revision ID: 689badf651d4
Revises: 45bdf764ff5f
Create Date: 2026-04-11 01:37:07.451539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689badf651d4'
down_revision: Union[str, Sequence[str], None] = '45bdf764ff5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('class_code_expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'class_code_expires_at')
    # ### end Alembic commands ###
