"""course_enrollment_student_id_nullable

Revision ID: b3e4e795107c
Revises: 689badf651d4
Create Date: 2026-04-11 01:48:38.277727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e4e795107c'
down_revision: Union[str, Sequence[str], None] = '689badf651d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_enrollments', 'student_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_enrollments', 'student_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
