"""remove_subject_from_classes

Revision ID: b56d1c96980c
Revises: 7b723d8a7388
Create Date: 2026-04-12 22:17:41.277169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56d1c96980c'
down_revision: Union[str, Sequence[str], None] = '7b723d8a7388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_subject_id'), table_name='classes')
    op.drop_constraint(op.f('classes_subject_id_fkey'), 'classes', type_='foreignkey')
    op.drop_column('classes', 'subject_id')
    op.drop_column('classes', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('classes_subject_id_fkey'), 'classes', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_classes_subject_id'), 'classes', ['subject_id'], unique=False)
    # ### end Alembic commands ###
