"""add_org_invitations_table

Revision ID: f35d9aa80269
Revises: 81042f403d56
Create Date: 2026-04-13 12:14:32.315691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35d9aa80269'
down_revision: Union[str, Sequence[str], None] = '81042f403d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('role_in_org', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'revoked', name='invitation_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_invitations_org_status', 'org_invitations', ['org_id', 'status'], unique=False)
    op.create_index('ix_org_invitations_user_status', 'org_invitations', ['invited_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_org_invitations_user_status', table_name='org_invitations')
    op.drop_index('ix_org_invitations_org_status', table_name='org_invitations')
    op.drop_table('org_invitations')
    # ### end Alembic commands ###
